{{- if and (not .Values.config.tokenSecret) .Values.config.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "github-exporter.fullname" . }}
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_EXPORTER_TOKEN: {{ .Values.config.token | b64enc }}
{{- end -}}
