{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "github-exporter.serviceAccountName" . }}
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
{{- end -}}
