{{- if and (not .Values.config.tokenSecret) .Values.config.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hcloud-exporter.fullname" . }}
  labels:
    {{- include "hcloud-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  HCLOUD_EXPORTER_TOKEN: {{ .Values.config.token | b64enc }}
{{- end -}}
