{{- if not .Values.config.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hcloud-exporter.fullname" . }}
  labels:
    {{- include "hcloud-exporter.labels" . | nindent 4 }}
type: Opaque
data:
   {{ .Values.config.tokenKey }}: {{ required "Requires token secret!" .Values.config.token | b64enc | quote }}
{{- end -}}
