{{- if not .Values.config.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hetzner-exporter.fullname" . }}
  labels:
    {{- include "hetzner-exporter.labels" . | nindent 4 }}
type: Opaque
data:
   {{ .Values.config.usernameKey }}: {{ required "Requires username secret!" .Values.config.username | b64enc | quote }}
   {{ .Values.config.passwordKey }}: {{ required "Requires password secret!" .Values.config.password | b64enc | quote }}
{{- end -}}
