{{- if not .Values.config.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "scw-exporter.fullname" . }}
  labels:
    {{- include "scw-exporter.labels" . | nindent 4 }}
type: Opaque
data:
   {{ .Values.config.accessKey }}: {{ default "" .Values.config.access | toString | b64enc | quote }}
   {{ .Values.config.secretKey }}: {{ default "" .Values.config.secret | toString | b64enc | quote }}
{{- end -}}
