{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "scw-exporter.serviceAccountName" . }}
  labels:
    {{- include "scw-exporter.labels" . | nindent 4 }}
{{- end -}}
