{{- if .Values.credentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-hetzner-sd.fullname" . }}-creds
  labels:
    {{- include "prometheus-hetzner-sd.labels" . | nindent 4 }}
stringData:
  credentials.yaml: |
    target:
      credentials:
        {{- toYaml .Values.credentials | nindent 8 }}
{{- end -}}
