{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-hetzner-sd.serviceAccountName" . }}
  labels:
    {{- include "prometheus-hetzner-sd.labels" . | nindent 4 }}
{{- end -}}
