---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: quay.io/promhippie/hcloud-exporter
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

serviceAccount:
  create: true
  name: ""

labels: {}
annotations: {}

securityContext:
  runAsGroup: 10000
  runAsUser: 10000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["all"]

service:
  type: ClusterIP
  port: 9501
  internalPort: 9501
  annotations: {}
  labels: {}
    # prometheus.io/path: /metrics
    # prometheus.io/port: "9501"
    # prometheus.io/scrape: "true"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

affinity: {}

tolerations: []

serviceMonitor:
  enabled: false
  namespace: ""
  labels: {}
  interval: 30s
  telemetryPath: /metrics
  timeout: 30s
  metricRelabelings: []
  relabelings: []
  targetLabels: []

prometheusRule:
  enabled: false
  namespace: ""
  additionalLabels: {}
  rules: []

envFromSecret: ""
envFromConfigMap: ""

extraEnvVariables: {}
extraEnvSecrets: {}

config:
  token:
  tokenSecret:

...
