{{- if not .Values.config.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dockerhub-exporter.fullname" . }}
  labels:
    {{- include "dockerhub-exporter.labels" . | nindent 4 }}
type: Opaque
data:
   {{ .Values.config.usernameKey }}: {{ default "" .Values.config.username | toString | b64enc | quote }}
   {{ .Values.config.passwordKey }}: {{ default "" .Values.config.password | toString | b64enc | quote }}
{{- end -}}
