{{- if and (not .Values.config.existingSecret) (ne .Values.config.authType "none") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "github-exporter.fullname" . }}
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
type: Opaque
data:
{{- if eq .Values.config.authType "token" }}
  {{ .Values.config.tokenKey }}: {{ default "" .Values.config.token | toString | b64enc | quote }}
{{- end }}
{{- if eq .Values.config.authType "app" }}
  {{ .Values.config.appIdKey }}: {{ default "" .Values.config.appId | toString | b64enc | quote }}
  {{ .Values.config.installationIdKey }}: {{ default "" .Values.config.installationId | toString | b64enc | quote }}
  {{ .Values.config.privateKeyKey }}: {{ default "" .Values.config.privateKey | b64enc | quote }}
{{- end }}
{{- end -}}
{{- if and (not .Values.webhook.existingSecret) .Values.webhook.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "github-exporter.webhookSecret" . }}
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.webhook.secretKey }}: {{ default "" .Values.webhook.secret | toString | b64enc | quote }}
{{- end -}}
{{- if and (not .Values.database.existingSecret) .Values.database.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "github-exporter.databaseSecret" . }}
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.dsnKey }}: {{ default "" .Values.database.dsn | toString | b64enc | quote }}
{{- end -}}
