{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jenkins-exporter.serviceAccountName" . }}
  labels:
    {{- include "jenkins-exporter.labels" . | nindent 4 }}
{{- end -}}
