{{- if .Values.files -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jenkins-exporter.fullname" . }}-files
  labels:
    {{- include "jenkins-exporter.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.files }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end -}}
