{{- if not .Values.config.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "scw-exporter.fullname" . }}
  labels:
    {{- include "scw-exporter.labels" . | nindent 4 }}
type: Opaque
data:
   {{ .Values.config.accessKey }}: {{ required "Requires access key!" .Values.config.access | b64enc | quote }}
   {{ .Values.config.secretKey }}: {{ required "Requires secret key!" .Values.config.secret | b64enc | quote }}
{{- end -}}
