---
name: helmdocs

"on":
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  helmdocs:
    runs-on: ubuntu-latest
    if: github.repository == 'promhippie/charts'

    steps:
      - name: Generate token
        id: token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.TOKEN_EXCHANGE_INSTALL }}
          private_key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permissions: >-
            {"contents": "write", "pull_requests": "write", "issues": "write"}

      - name: Checkout source
        id: source
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token }}
          fetch-depth: 0

      - name: Update readme
        id: docs
        uses: docker://jnorwood/helm-docs:v1.11.3
        with:
          entrypoint: helm-docs

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: stable/
          message: "docs: automated readme updates"
          push: false
          commit: --signoff

      - name: Create request
        id: request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update/readme
          delete-branch: true
          title: "docs: automated readme updates"
          body: "New readmes generated, automerge should handle that!"
          labels: docs
          token: ${{ steps.token.outputs.token }}

      - name: Approve request
        id: approve
        if: steps.request.outputs.pull-request-operation == 'created'
        run: gh pr review --approve "${{ steps.request.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable automerge
        id: automerge
        if: steps.request.outputs.pull-request-operation == 'created'
        run: gh pr merge --rebase --auto "${{ steps.request.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue
        id: issue
        if: failure()
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
          GITHUB_SERVER_URL: ${ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        with:
          filename: .github/workflow-issue.md
          update_existing: true
          search_existing: open

...
