---
name: helmdocs

"on":
  workflow_dispatch:
  push:
    branches:
      - master

permissions: read-all

jobs:
  helmdocs:
    runs-on: ubuntu-latest
    if: github.repository == 'promhippie/charts'

    steps:
      - name: Generate token
        id: token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.TOKEN_EXCHANGE_INSTALL }}
          private_key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permissions: >-
            {"contents": "write"}

      - name: Checkout source
        id: source
        uses: actions/checkout@v4
        with:
          token: ${{ steps.token.outputs.token }}
          fetch-depth: 0

      - name: Update readme
        id: docs
        uses: docker://jnorwood/helm-docs:v1.11.3
        with:
          entrypoint: helm-docs

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          add: stable/
          message: "docs: automated readme update [skip ci]"
          push: true
          commit: --signoff

...
