---
name: helmdocs

"on":
  push:
    branches:
      - master

jobs:
  helmdocs:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Update readme
        uses: docker://jnorwood/helm-docs:v1.7.0
        with:
          entrypoint: helm-docs

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: github@webhippie.de
          add: charts/
          message: automated readme update [skip ci]
          push: true
          commit: --signoff

...
