---
name: release

"on":
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Import gnupg
        uses: cresh-io/action-gpg@v1
        with:
          gpg-sign-key: ${{ secrets.GNUPG_KEY }}
          gpg-passphrase: ${{ secrets.GNUPG_PASSWORD }}
          git-email: ${{ github.actor }}@users.noreply.github.com
          git-username: ${{ github.actor }}

      - name: Run releaser
        id: releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

...
